### ISSUE TITLE
FreeIPA nightly test failure in ipa-server-install with NoClassDefFoundError: org/apache/commons/lang3/StringUtils

### ISSUE THREAD

**Issue by flo-renaud** [dogtagpki/pki#3366]
FreeIPA nightly tests using the updates-testing repository are failing in ipa-server-install, during the CA installation step. See the PR #[509](https://github.com/freeipa-pr-ci2/freeipa/pull/509) for instance.

The ipa-server-install logs display the following message:
```
DEBUG: Command: sudo -u pkiuser /usr/lib/jvm/jre-openjdk/bin/java -classpath /usr/share/tomcat/bin/tomcat-juli.jar:/usr/share/java/tomcat-servlet-api.jar:/usr/share/pki/ca/webapps/ca/WEB-INF/lib/*:/var/lib/pki/pki-tomcat/common/lib/*:/usr/share/pki/lib/* -Djavax.sql.DataSource.Factory=org.apache.commons.dbcp.BasicDataSourceFactory -Dcatalina.base=/var/lib/pki/pki-tomcat -Dcatalina.home=/usr/share/tomcat -Djava.endorsed.dirs= -Djava.io.tmpdir=/var/lib/pki/pki-tomcat/temp -Djava.util.logging.config.file=/etc/pki/pki-tomcat/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Dcom.redhat.fips=false org.dogtagpki.server.cli.PKIServerCLI ca-db-remove --force --debug
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at org.apache.tomcat.util.net.jss.TomcatJSS.loadTomcatConfig(TomcatJSS.java:343)
	at org.apache.tomcat.util.net.jss.TomcatJSS.loadTomcatConfig(TomcatJSS.java:302)
	at org.apache.tomcat.util.net.jss.TomcatJSS.loadTomcatConfig(TomcatJSS.java:293)
	at org.dogtagpki.server.cli.SubsystemDBRemoveCLI.execute(SubsystemDBRemoveCLI.java:67)
	at org.dogtagpki.cli.CommandCLI.execute(CommandCLI.java:57)
	at org.dogtagpki.cli.CLI.execute(CLI.java:352)
	at org.dogtagpki.cli.CLI.execute(CLI.java:352)
	at org.dogtagpki.cli.CLI.execute(CLI.java:352)
	at org.dogtagpki.server.cli.PKIServerCLI.execute(PKIServerCLI.java:86)
	at org.dogtagpki.server.cli.PKIServerCLI.main(PKIServerCLI.java:92)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 10 more
ERROR: CalledProcessError: Command '['sudo', '-u', 'pkiuser', '/usr/lib/jvm/jre-openjdk/bin/java', '-classpath', '/usr/share/tomcat/bin/tomcat-juli.jar:/usr/share/java/tomcat-servlet-api.jar:/usr/share/pki/ca/webapps/ca/WEB-INF/lib/*:/var/lib/pki/pki-tomcat/common/lib/*:/usr/share/pki/lib/*', '-Djavax.sql.DataSource.Factory=org.apache.commons.dbcp.BasicDataSourceFactory', '-Dcatalina.base=/var/lib/pki/pki-tomcat', '-Dcatalina.home=/usr/share/tomcat', '-Djava.endorsed.dirs=', '-Djava.io.tmpdir=/var/lib/pki/pki-tomcat/temp', '-Djava.util.logging.config.file=/etc/pki/pki-tomcat/logging.properties', '-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager', '-Dcom.redhat.fips=false', 'org.dogtagpki.server.cli.PKIServerCLI', 'ca-db-remove', '--force', '--debug']' returned non-zero exit status 1.
  File "/usr/lib/python3.8/site-packages/pki/server/pkispawn.py", line 575, in main
    scriptlet.spawn(deployer)
  File "/usr/lib/python3.8/site-packages/pki/server/deployment/scriptlets/configuration.py", line 820, in spawn
    subsystem.remove_database(force=True)
  File "/usr/lib/python3.8/site-packages/pki/server/subsystem.py", line 945, in remove_database
    self.run(cmd, as_current_user=as_current_user)
  File "/usr/lib/python3.8/site-packages/pki/server/subsystem.py", line 1137, in run
    subprocess.run(cmd, check=True)
  File "/usr/lib64/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
```

Companion issue [8561](https://pagure.io/freeipa/issue/8561) on freeipa side.

This is high prio since it is blocking ipa server installation when updates-testing is enabled.

Installed packages:
pki-server-10.9.4-1.fc32.noarch
tomcat-9.0.38-2.fc32.noarch
tomcatjss-7.6.0-1.fc32.noarch

**Comment by cipherboy** [comment]
@flo-renaud -- this is because the PKI and TomcatJSS versions are mismatched -- PKI v10.10 is the current release across F32+ and contains ACL3 that TomcatJSS 7.6.0 depends on. See: 

https://github.com/dogtagpki/pki/blob/master/pki.spec#L15-L17
https://github.com/dogtagpki/pki/blob/master/pki.spec#L225-L226
https://github.com/dogtagpki/pki/blob/master/pki.spec#L173
https://github.com/dogtagpki/pki/blob/master/pki.spec#L420
https://github.com/dogtagpki/tomcatjss/blob/master/tomcatjss.spec#L44

Please fix this mismatch and it will work.

https://bodhi.fedoraproject.org/updates/FEDORA-2020-b115578381 has all of the F32 packages in a single Bodhi. How did 10.9.4. manage to get pulled with TomcatJSS, even though they came from the same Bodhi?

**Comment by flo-renaud** [comment]
@cipherboy 
With the current tomcatjss.spec, it is possible to update tomcatjss without triggering pki-server upgrade:
```
# rpm -qa pki-base tomcatjss
tomcatjss-7.5.0-1.fc32.noarch
pki-base-10.9.4-1.fc32.noarch
# dnf update -y --enablerepo=updates-testing tomcatjss
[...]
# rpm -qa pki-base tomcatjss
tomcatjss-7.6.0-1.fc32.noarch
pki-base-10.9.4-1.fc32.noarch
```

The tomcatjss spec could be updated to conflict with pki-base < 10.10, see line:
https://github.com/dogtagpki/tomcatjss/blob/master/tomcatjss.spec#L90

**Comment by cipherboy** [comment]
https://github.com/dogtagpki/jss/pull/654
https://github.com/dogtagpki/tomcatjss/pull/29

**Comment by cipherboy** [comment]
Built and in the Bodhi update, closing.
