### ISSUE TITLE
FreeIPA nightly test failure in replica install: IllegalArgumentException: Illegal base64 character 2e

### ISSUE THREAD

**Issue by flo-renaud** [dogtagpki/pki#3370]
FreeIPA nightly test randomly failed in ipa-replica-install while configuring the CA clone. More information available in PR #[5112](https://github.com/freeipa-pr-ci2/freeipa/pull/512) with the [logs](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/f4bbef8e-1d35-11eb-a86e-fa163e6c3b05/test_integration-test_replication_layouts.py-TestCompleteTopologyWithCAKRA-test_complete_topology_with_ca_kra/).

replica2 installation fails while getting the ssl server certificate from the master, and the master [logs](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/f4bbef8e-1d35-11eb-a86e-fa163e6c3b05/test_integration-test_replication_layouts.py-TestCompleteTopologyWithCAKRA-test_complete_topology_with_ca_kra/master.ipa.test/var/log/pki/pki-tomcat/ca/debug.2020-11-02.log.gz) display:
```
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO: TokenAuthentication: Authenticating session ID against security domain at https://master.ipa.test:8443/ca/admin/ca/tokenAuthenticate
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO: HTTP request: POST /ca/admin/ca/tokenAuthenticate HTTP/1.1
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO:   Content-Type: application/x-www-form-urlencoded
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO:   Content-Length: 54
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO:   Host: master.ipa.test:8443
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO:   Connection: Keep-Alive
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO:   User-Agent: Apache-HttpClient/4.5.10 (Java/1.8.0_265)
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO: HTTP response: HTTP/1.1 200 
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO:   Content-Type: application/xml
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO:   Content-Length: 172
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO:   Date: Mon, 02 Nov 2020 18:39:47 GMT
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO:   Keep-Alive: timeout=300
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO:   Connection: keep-alive
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO: EnrollProfile: Parsing PKCS #10 request:
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO: EnrollProfile: createEnrollmentRequest 21
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] WARNING: Invalid base64: [admin-replica2.ipa.test]: java.lang.IllegalArgumentException: Illegal base64 character 2e
java.lang.IllegalArgumentException: Illegal base64 character 2e
	at java.util.Base64$Decoder.decode0(Base64.java:714)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at org.mozilla.jss.netscape.security.util.Utils.base64decode(Utils.java:415)
	at org.dogtagpki.server.authentication.AuthToken.getInByteArray(AuthToken.java:113)
	at org.dogtagpki.server.authentication.AuthToken.getInStringArray(AuthToken.java:198)
	at com.netscape.cms.servlet.cert.CertProcessor.setAuthTokenIntoRequest(CertProcessor.java:132)
	at com.netscape.cms.servlet.cert.CertProcessor.populateRequests(CertProcessor.java:345)
	at com.netscape.cms.servlet.cert.EnrollmentProcessor.processEnrollment(EnrollmentProcessor.java:189)
	at com.netscape.cms.servlet.cert.EnrollmentProcessor.processEnrollment(EnrollmentProcessor.java:97)
	at com.netscape.cms.servlet.profile.ProfileSubmitServlet.processEnrollment(ProfileSubmitServlet.java:276)
	at com.netscape.cms.servlet.profile.ProfileSubmitServlet.process(ProfileSubmitServlet.java:130)
	at com.netscape.cms.servlet.base.CMSServlet.service(CMSServlet.java:494)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:170)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:225)
	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:191)
	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at com.netscape.cms.tomcat.ExternalAuthenticationValve.invoke(ExternalAuthenticationValve.java:82)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:431)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

Companion issue on freeipa side: https://pagure.io/freeipa/issue/8564

Installed [packages](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/f4bbef8e-1d35-11eb-a86e-fa163e6c3b05/installed_packages/):
pki-server-10.9.0-0.4.fc32.noarch
tomcat-9.0.36-1.fc32.noarch
tomcatjss-7.5.0-0.4.fc32.noarch

**Comment by cipherboy** [comment]
More log output afterwards seems relevant:

```
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO: CertProcessor: - req_seq_num: 0
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO: CertProcessor: - profilesetid: serverCertSet
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO: CertProcessor: - req_subject_name.uid: 
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO: CertProcessor: - auth_token.groups[0]: Enterprise CA Administrators
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO: CertProcessor: - profileremoteaddr: 192.168.122.219
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO: CertProcessor: - requesttype: enrollment
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO: CertProcessor: - req_extensions: owIwAA==

2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO: CertProcessor: - req_subject_name: MC8xETAPBgNVBAoMCElQQS5URVNUMRowGAYDVQQDDBFyZXBsaWNhMi5pcGEudGVzdA==

2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO: CertProcessor: - profileremotehost: 192.168.122.219
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO: CertProcessor: Submitting certificate request to caInternalAuthServerCert profile
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO: KeyConstraint: Key algorithnm: RSA
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO: KeyConstraint: Key type: RSA
2020-11-02 18:39:47 [ajp-nio-127.0.0.1-8009-exec-2] INFO: CA is going to sign certificate serial number 0x15
2020-11-02 18:41:33 [CertStatusUpdateTask] INFO: DBVirtualList: Searching ou=certificateRepository, ou=ca, o=ipaca
2020-11-02 18:41:34 [Timer-0] INFO: SessionTimer: checking security domain sessions
2020-11-02 18:41:33 [SerialNumberUpdateTask] INFO: SerialNumberUpdateTask: updating serial numbers
2020-11-02 18:43:15 [CertStatusUpdateTask] INFO: DBVirtualList: filter: (certStatus=INVALID)
2020-11-02 18:43:15 [ajp-nio-127.0.0.1-8009-exec-2] INFO: CA stored signed certificate serial number 0x15
2020-11-02 18:43:15 [ajp-nio-127.0.0.1-8009-exec-2] INFO: enrollment reqID 21 fromAgent userID: admin-replica2.ipa.test authenticated by TokenAuth is completed DN requested: CN=replica2.ipa.test,O=IPA.TEST cert issued serial number: 0x15 time: 208216
2020-11-02 18:43:15 [ajp-nio-127.0.0.1-8009-exec-2] INFO: Updating certificate request
2020-11-02 18:43:15 [CertStatusUpdateTask] INFO: DBVirtualList: Searching ou=certificateRepository, ou=ca, o=ipaca
2020-11-02 18:43:15 [CertStatusUpdateTask] INFO: DBVirtualList: filter: (certStatus=VALID)
2020-11-02 18:43:15 [CertStatusUpdateTask] INFO: DBVirtualList: dn: cn=14,ou=certificateRepository,ou=ca,o=ipaca
2020-11-02 18:43:15 [CertStatusUpdateTask] INFO: DBVirtualList: Searching ou=certificateRepository, ou=ca, o=ipaca
2020-11-02 18:43:15 [CertStatusUpdateTask] INFO: DBVirtualList: filter: (certStatus=REVOKED)
2020-11-02 18:43:15 [Finalizer] SEVERE: WARNING: SSL alert sent: CLOSE_NOTIFY
2020-11-02 18:43:15 [Finalizer] SEVERE: WARNING: SSL alert sent: CLOSE_NOTIFY
2020-11-02 18:43:16 [ajp-nio-127.0.0.1-8009-exec-2] WARNING: Error getting servlet output stream when rendering  template. Error org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe.
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:351)
	at org.apache.catalina.connector.OutputBuffer.flushByteBuffer(OutputBuffer.java:776)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:298)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:272)
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:118)
	at com.netscape.cms.servlet.base.CMSServlet.outputResult(CMSServlet.java:2110)
	at com.netscape.cms.servlet.profile.ProfileSubmitServlet.xmlOutput(ProfileSubmitServlet.java:451)
	at com.netscape.cms.servlet.profile.ProfileSubmitServlet.process(ProfileSubmitServlet.java:181)
	at com.netscape.cms.servlet.base.CMSServlet.service(CMSServlet.java:494)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:170)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:225)
	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:191)
	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:47)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:145)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at com.netscape.cms.tomcat.ExternalAuthenticationValve.invoke(ExternalAuthenticationValve.java:82)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:431)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:468)
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:138)
	at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101)
	at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:152)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1253)
	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:740)
	at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:693)
	at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:683)
	at org.apache.coyote.ajp.AjpProcessor.writeData(AjpProcessor.java:1259)
	at org.apache.coyote.ajp.AjpProcessor.access$600(AjpProcessor.java:57)
	at org.apache.coyote.ajp.AjpProcessor$SocketOutputBuffer.doWrite(AjpProcessor.java:1331)
	at org.apache.coyote.Response.doWrite(Response.java:601)
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:339)
	... 58 more
```

**Comment by fcami** [comment]
We haven't seen this in a while. Could you please close this issue @ladycfu ?

**Comment by ladycfu** [comment]
ok. closing per request from @fcami
