### ISSUE TITLE
ipa-replica-install fails to reinstall a replica (rawhide)

### ISSUE THREAD

**Issue by flo-renaud** [dogtagpki/pki#3544]
The nightly test `test_server_del` is failing on rawhide with pki-server-10.11.0-0.1.alpha1.fc35.noarch.
See PR #[921](https://github.com/freeipa-pr-ci2/freeipa/pull/921) with the following [logs](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/ab35f700-bb15-11eb-afe7-fa163ee0f681/) and [report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/ab35f700-bb15-11eb-afe7-fa163ee0f681/report.html):
```
self = <ipatests.test_integration.test_server_del.TestServerDel object at 0x7f3fd52a0490>

    def test_ignore_topology_disconnect_replica1(self):
        """
        tests that removal of replica1 with '--ignore-topology-disconnect'
        destroys master for good
        """
        check_master_removal(
            self.client,
            self.replica1.hostname,
            ignore_topology_disconnect=True
        )
    
        # reinstall the replica
        tasks.uninstall_master(self.replica1)
>       tasks.install_replica(self.master, self.replica1, setup_ca=True)

test_integration/test_server_del.py:184: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pytest_ipa/integration/tasks.py:512: in install_replica
    result = replica.run_command(args, raiseonerr=raiseonerr,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ipatests.pytest_ipa.integration.host.Host replica1.ipa.test (replica)>
argv = ['ipa-replica-install', '--admin-password', 'Secret.123', '--password', 'Secret.123', '-U', ...]
set_env = True, stdin_text = None, log_stdout = True, raiseonerr = True
cwd = None, bg = False, encoding = 'utf-8', ok_returncode = 0

    def run_command(self, argv, set_env=True, stdin_text=None,
                    log_stdout=True, raiseonerr=True,
                    cwd=None, bg=False, encoding='utf-8', ok_returncode=0):
        """Wrapper around run_command to log stderr on raiseonerr=True
    
        :param ok_returncode: return code considered to be correct,
                              you can pass an integer or sequence of integers
        """
        result = super().run_command(
            argv, set_env=set_env, stdin_text=stdin_text,
            log_stdout=log_stdout, raiseonerr=False, cwd=cwd, bg=bg,
            encoding=encoding
        )
        # in FIPS mode SSH may print noise to stderr, remove the string
        # "FIPS mode initialized" + optional newline.
        result.stderr_bytes = FIPS_NOISE_RE.sub(b'', result.stderr_bytes)
        try:
            result_ok = result.returncode in ok_returncode
        except TypeError:
            result_ok = result.returncode == ok_returncode
        if not result_ok and raiseonerr:
            result.log.error('stderr: %s', result.stderr_text)
>           raise subprocess.CalledProcessError(
                result.returncode, argv,
                result.stdout_text, result.stderr_text
            )
E           subprocess.CalledProcessError: Command '['ipa-replica-install', '--admin-password', 'Secret.123', '--password', 'Secret.123', '-U', '--setup-ca', '--ip-address', '192.168.122.65', '--realm', 'IPA.TEST', '--domain', 'ipa.test', '--dirsrv-config-file', '/ipatests/ipatests_dse.ldif']' returned non-zero exit status 1.

pytest_ipa/integration/host.py:202: CalledProcessError
 ------------------------------Captured stderr call------------------------------ 
ipa: WARNING: ipa: ERROR: DNS zone with name "122.168.192.in-addr.arpa." already exists

ipa: ERROR: stderr: Lookup failed: Preferred host replica1.ipa.test does not provide DNS.
Reverse DNS resolution of address 192.168.122.26 (master.ipa.test) failed. Clients may not function properly. Please check your DNS setup. (Note that this check queries IPA DNS directly and ignores /etc/hosts.)
Replica DNS records could not be added on master: Insufficient access: Insufficient 'add' privilege to add the entry 'idnsname=replica1,idnsname=ipa.test.,cn=dns,dc=ipa,dc=test'.
Custodia uses 'master.ipa.test' as master peer.
Failed to configure CA instance
See the installation logs and the following files/directories for more information:
  /var/log/pki/pki-tomcat
CA configuration failed.
The ipa-replica-install command failed. See /var/log/ipareplica-install.log for more information
```

Test scenario:
- install first server
- install replica
- uninstall replica
- re-install replica

The test is failing in a call to pkispawn, with an error trying to add the entry "uid=CA-replica1.ipa.test-8443,ou=People,o=ipaca" (entry already exists).

Companion issue on ipa side: https://pagure.io/freeipa/issue/8865

**Comment by flo-renaud** [comment]
More information to help investigations:
the [ipareplica-install.log](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/ab35f700-bb15-11eb-afe7-fa163ee0f681/test_integration-test_server_del.py-TestServerDel-test_ignore_topology_disconnect_replica1/replica1.ipa.test/var/log/ipareplica-install.log.gz) contains the contents of pkispawn configuration file (look for the string "Contents of pkispawn configuration file"), as well as the pkispawn output. Relevant lines:
```
INFO: Adding CA-replica1.ipa.test-8443
DEBUG: Command: /usr/sbin/runuser -u pkiuser -- /usr/bin/env java -classpath /usr/share/tomcat/bin/tomcat-juli.jar:/usr/share/java/tomcat-servlet-api.jar:/usr/share/pki/ca/webapps/ca/WEB-INF/lib/*:/var/lib/pki/pki-tomcat/common/lib/*:/usr/share/pki/lib/* -Djavax.sql.DataSource.Factory=org.apache.commons.dbcp.BasicDataSourceFactory -Dcatalina.base=/var/lib/pki/pki-tomcat -Dcatalina.home=/usr/share/tomcat -Djava.endorsed.dirs= -Djava.io.tmpdir=/var/lib/pki/pki-tomcat/temp -Djava.util.logging.config.file=/etc/pki/pki-tomcat/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Dcom.redhat.fips=false org.dogtagpki.server.cli.PKIServerCLI ca-user-add --full-name CA-replica1.ipa.test-8443 --type agentType --state 1 --debug CA-replica1.ipa.test-8443
INFO: Loading /var/lib/pki/pki-tomcat/ca/conf/CS.cfg
FINE: PlainPasswordFile: Initializing PlainPasswordFile
FINE: PlainPasswordFile: - internal: ********
FINE: PlainPasswordFile: - internaldb: ********
FINE: PlainPasswordFile: - replicationdb: ********
FINE: LdapAuthInfo: init()
FINE: LdapAuthInfo: init begins
FINE: LdapAuthInfo: init ends
FINE: TCP Keep-Alive: true
FINE: Creating LdapBoundConnFactor(UGSubsystem)
FINE: LdapBoundConnFactory: initialization
FINE: LdapAuthInfo: init()
FINE: LdapAuthInfo: init begins
FINE: LdapAuthInfo: init ends
FINE: LdapBoundConnFactory: doCloning: true
FINE: LdapBoundConnFactory: mininum: 3
FINE: LdapBoundConnFactory: maximum: 15
FINE: LdapBoundConnFactory: host: replica1.ipa.test
FINE: LdapBoundConnFactory: port: 636
FINE: LdapBoundConnFactory: secure: true
FINE: LdapBoundConnFactory: authentication: 1
FINE: LdapBoundConnFactory: makeConnection(false)
FINE: TCP Keep-Alive: true
FINE: LdapAuthInfo: init: prompt is internaldb
FINE: LdapAuthInfo: init: try getting from memory cache
FINE: LdapAuthInfo: init: password not in memory
FINE: LdapAuthInfo: getPasswordFromStore: try to get it from password store
FINE: LdapAuthInfo: getPasswordFromStore: about to get from passwored store: internaldb
FINE: LdapAuthInfo: getPasswordFromStore: password store available
FINE: LdapAuthInfo: getPasswordFromStore: password found for prompt in password store
FINE: LdapAuthInfo: password ok: store in memory cache
FINE: LdapBoundConnection: Connecting to replica1.ipa.test:636 with basic auth as cn=Directory Manager
FINE: ldapconn/PKISocketFactory.makeSSLSocket: begins
FINE: PKIClientSocketListener.handshakeCompleted: begins
FINE: Handshake completed:
FINE: - client: 192.168.122.65
FINE: - server: 192.168.122.65
FINE: - subject: SYSTEM
FINE: SignedAuditLogger: event CLIENT_ACCESS_SESSION_ESTABLISH
FINE: PKIClientSocketListener.handshakeCompleted: CS_CLIENT_ACCESS_SESSION_ESTABLISH_SUCCESS
FINE: PKIClientSocketListener.handshakeCompleted: clientIP=192.168.122.65 serverIP=192.168.122.65 serverPort=636
FINE: SSL handshake happened
FINE: LdapBoundConnFactory: increasing minimum connections by 3
FINE: LdapBoundConnFactory: total connections: 3
FINE: LdapBoundConnFactory: number of connections: 3
INFO: Adding uid=CA-replica1.ipa.test-8443,ou=People,o=ipaca
FINE: UGSubsystem: - objectclass: [top, person, organizationalPerson, inetOrgPerson, cmsuser]
FINE: UGSubsystem: - uid: CA-replica1.ipa.test-8443
FINE: UGSubsystem: - sn: CA-replica1.ipa.test-8443
FINE: UGSubsystem: - cn: CA-replica1.ipa.test-8443
FINE: UGSubsystem: - usertype: agentType
FINE: UGSubsystem: - userstate: 1
INFO: Admin UID: null added User UID: CA-replica1.ipa.test-8443
FINE: LdapBoundConnFactory: getting a connection
FINE: LdapBoundConnFactory: master connection is connected: true
FINE: LdapBoundConnFactory: connection already connected: true
FINE: LdapBoundConnFactory: number of connections: 2
FINE: LdapBoundConnFactory: number of connections: 3
FINE: Destroying LdapBoundConnFactory(UGSubsystem)
FINE: LdapBoundConnFactory: disconnecting master connection
FINE: PKIClientSocketListener.alertReceived: begins
FINE: SSL alert received:
FINE: - reason: CLOSE_NOTIFY
FINE: - client: 192.168.122.65
FINE: - server: 192.168.122.65
FINE: - subject: SYSTEM
FINE: SignedAuditLogger: event CLIENT_ACCESS_SESSION_TERMINATED
FINE: PKIClientSocketListener.alertReceived: CS_CLIENT_ACCESS_SESSION_TERMINATED
FINE: PKIClientSocketListener.alertReceived: clientIP=192.168.122.65 serverIP=192.168.122.65 serverPort=636 reason=CLOSE_NOTIFY
FINE: PKIClientSocketListener.alertSent: begins
FINE: PKIClientSocketListener.alertSent: got description:0
FINE: PKIClientSocketListener.alertSent: got reason:CLOSE_NOTIFY
FINE: PKIClientSocketListener.alertSent: CS_CLIENT_ACCESS_SESSION_TERMINATED
FINE: PKIClientSocketListener.alertSent: clientIP=192.168.122.65 serverIP=192.168.122.65 serverPort=636 reason=CLOSE_NOTIFY
FINE: SSL alert sent:
FINE: - reason: CLOSE_NOTIFY
FINE: - client: 192.168.122.65
FINE: - server: 192.168.122.65
FINE: - subject: SYSTEM
FINE: SignedAuditLogger: event CLIENT_ACCESS_SESSION_TERMINATED
FINE: PKIClientSocketListener.alertSent: CS_CLIENT_ACCESS_SESSION_ESTABLISH_FAILURE
FINE: PKIClientSocketListener.alertSent: clientIP=192.168.122.65 serverIP=192.168.122.65 serverPort=636 reason=CLOSE_NOTIFY
com.netscape.certsrv.base.ConflictingOperationException: Entry already exists.
	at com.netscape.certsrv.ldap.LDAPExceptionConverter.toPKIException(LDAPExceptionConverter.java:45)
	at com.netscape.cmscore.usrgrp.UGSubsystem.addUser(UGSubsystem.java:720)
	at org.dogtagpki.server.cli.SubsystemUserAddCLI.execute(SubsystemUserAddCLI.java:167)
	at org.dogtagpki.cli.CommandCLI.execute(CommandCLI.java:57)
	at org.dogtagpki.cli.CLI.execute(CLI.java:357)
	at org.dogtagpki.cli.CLI.execute(CLI.java:357)
	at org.dogtagpki.cli.CLI.execute(CLI.java:357)
	at org.dogtagpki.server.cli.PKIServerCLI.execute(PKIServerCLI.java:90)
	at org.dogtagpki.server.cli.PKIServerCLI.main(PKIServerCLI.java:120)
Caused by: netscape.ldap.LDAPException: error result (68); Already exists
	at netscape.ldap.LDAPConnection.checkMsg(Unknown Source)
	at netscape.ldap.LDAPConnection.add(Unknown Source)
	at netscape.ldap.LDAPConnection.add(Unknown Source)
	at netscape.ldap.LDAPConnection.add(Unknown Source)
	at com.netscape.cmscore.usrgrp.UGSubsystem.addUser(UGSubsystem.java:717)
	... 7 more
CalledProcessError: Command '['/usr/sbin/runuser', '-u', 'pkiuser', '--', '/usr/bin/env', 'java', '-classpath', '/usr/share/tomcat/bin/tomcat-juli.jar:/usr/share/java/tomcat-servlet-api.jar:/usr/share/pki/ca/webapps/ca/WEB-INF/lib/*:/var/lib/pki/pki-tomcat/common/lib/*:/usr/share/pki/lib/*', '-Djavax.sql.DataSource.Factory=org.apache.commons.dbcp.BasicDataSourceFactory', '-Dcatalina.base=/var/lib/pki/pki-tomcat', '-Dcatalina.home=/usr/share/tomcat', '-Djava.endorsed.dirs=', '-Djava.io.tmpdir=/var/lib/pki/pki-tomcat/temp', '-Djava.util.logging.config.file=/etc/pki/pki-tomcat/logging.properties', '-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager', '-Dcom.redhat.fips=false', 'org.dogtagpki.server.cli.PKIServerCLI', 'ca-user-add', '--full-name', 'CA-replica1.ipa.test-8443', '--type', 'agentType', '--state', '1', '--debug', 'CA-replica1.ipa.test-8443']' returned non-zero exit status 255.
  File "/usr/lib/python3.9/site-packages/pki/server/pkispawn.py", line 575, in main
    scriptlet.spawn(deployer)
  File "/usr/lib/python3.9/site-packages/pki/server/deployment/scriptlets/configuration.py", line 740, in spawn
    deployer.setup_subsystem_user(instance, subsystem, system_certs['subsystem'])
  File "/usr/lib/python3.9/site-packages/pki/server/deployment/__init__.py", line 1033, in setup_subsystem_user
    subsystem.add_user(
  File "/usr/lib/python3.9/site-packages/pki/server/subsystem.py", line 1506, in add_user
    self.run(
  File "/usr/lib/python3.9/site-packages/pki/server/subsystem.py", line 1634, in run
    return subprocess.run(
  File "/usr/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
```

This corresponds to pkispawn trying to add an entry in LDAP while the entry already exists (dirsrv [access logs](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/ab35f700-bb15-11eb-afe7-fa163ee0f681/test_integration-test_server_del.py-TestServerDel-test_ignore_topology_disconnect_replica1/replica1.ipa.test/var/log/dirsrv/slapd-IPA-TEST/access.gz)):
```
[22/May/2021:16:53:32.406704269 +0000] conn=36 op=2 ADD dn="uid=CA-replica1.ipa.test-8443,ou=People,o=ipaca"
[22/May/2021:16:53:32.413138690 +0000] conn=36 op=2 RESULT err=68 tag=105 nentries=0 wtime=0.000322237 optime=0.006441181 etime=0.006745727
```

**Comment by edewata** [comment]
The build is available from this COPR repo:
https://copr.fedorainfracloud.org/coprs/g/pki/master/builds/

**Comment by flo-renaud** [comment]
Thanks @edewata , I verified that the test now succeeds with dogtag-pki-base-11.1.0-0.1.alpha1.20211102190529UTC.ec45bb54.fc36.noarch

**Comment by edewata** [comment]
Thanks!
