### ISSUE TITLE
CRMF request fail with error message NullPointerException Fedora 33 

### ISSUE THREAD

**Issue by dpuniaredhat** [dogtagpki/pki#3656]
Upstream, CRMF request fail with the error message "java.lang.NullPointerException"

#pki -d nssdb/ -P https -p 20443 -h pki1.example.com -c SECret.123 -n 'PKI CA Administrator for Example.Org' client-cert-request  "CN=foo1" --algorithm rsa --length 2048 --profile caOtherCert --type crmf
java.lang.NullPointerException
	at com.netscape.cmstools.CRMFPopClient.getKeyWrapAlgotihm(CRMFPopClient.java:630)
	at com.netscape.cmstools.client.ClientCertRequestCLI.execute(ClientCertRequestCLI.java:302)
	at org.dogtagpki.cli.CommandCLI.execute(CommandCLI.java:58)
	at org.dogtagpki.cli.CLI.execute(CLI.java:357)
	at org.dogtagpki.cli.CLI.execute(CLI.java:357)
	at com.netscape.cmstools.cli.MainCLI.execute(MainCLI.java:656)
	at com.netscape.cmstools.cli.MainCLI.main(MainCLI.java:694)

CA debug logs:

2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINE: SessionContextInterceptor: CASystemCertResource.getTransportCert()
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINE: SessionContextInterceptor: Not authenticated.
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINE: AuthMethodInterceptor: CASystemCertResource.getTransportCert()
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINE: AuthMethodInterceptor: mapping: default
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINE: AuthMethodInterceptor: required auth methods: [*]
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINE: AuthMethodInterceptor: anonymous access allowed
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINE: ACLInterceptor: CASystemCertResource.getTransportCert()
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINE: ACLInterceptor.filter: no authorization required
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINE: ACLInterceptor: No ACL mapping; authz not required.
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINE: SignedAuditLogger: event AUTHZ
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Getting pidDir=/var/run/pki/tomcat
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Getting pidDir=/var/run/pki/tomcat
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINE: MessageFormatInterceptor: CASystemCertResource.getTransportCert()
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINE: MessageFormatInterceptor: accept: [application/json]
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINE: MessageFormatInterceptor: response format: application/json
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Property processor.kraconnector.profileId not found
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Getting processor.kraconnector.profileId=
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Property processor.kraconnector.authzResourceName not found
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Getting processor.kraconnector.authzResourceName=
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Property processor.kraconnector.authMgr not found
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Getting processor.kraconnector.authMgr=
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Property processor.kraconnector.getClientCert not found
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Getting processor.kraconnector.getClientCert=
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Property processor.kraconnector.profileSubId not found
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Getting processor.kraconnector.profileSubId=
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Property processor.kraconnector.ACLinfo not found
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Getting processor.kraconnector.ACLinfo=
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Property processor.kraconnector.authzMgr not found
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Getting processor.kraconnector.authzMgr=
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Getting authz.sourceType=ldap
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Getting authz.sourceType=ldap
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINE: ServletUtils: according to ccMode, authorization for servlet: kraconnector is LDAP based, not XML {1}, use default authz mgr: {2}.
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Getting ca.connector.KRA.host=pki1.example.com
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Getting ca.connector.KRA.port=21443
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Getting ca.connector.KRA.enable=true
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Getting ca.connector.KRA.local=false
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Getting ca.connector.KRA.timeout=30
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Getting ca.connector.KRA.uri=/kra/agent/kra/connector
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-23] FINEST: Getting ca.connector.KRA.transportCert=MIIDzjCCAragAwIBAgIBEjANBgkqhkiG9w0BAQ0FADBhMSUwIwYDVQQKDBx0b3BvbG9neS0wM19Gb29iYXJtYXN0ZXIub3JnMRcwFQYDVQQLDA50b3BvbG9neS0wMy1DQTEfMB0GA1UEAwwWQ0EgU2lnbmluZyBDZXJ0aWZpY2F0ZTAeFw0yMTA3MTUwNzA1NTFaFw0yMzA3MDUwNzA1NTFaMGUxJTAjBgNVBAoUHHRvcG9sb2d5LTAzX0Zvb2Jhcm1hc3Rlci5vcmcxGDAWBgNVBAsTD3RvcG9sb2d5LTAzLUtSQTEiMCAGA1UEAxMZRFJNIFRyYW5zcG9ydCBDZXJ0aWZpY2F0ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKmSskoGKHEBVzy6tA0+t2LGOqEh/ZcMxLlhPCg9VpNfxAVx/W6ATcvWR6F1dkr1SYXFpHd5WwWp6i/7sjRoAmLqtqQHNP9Z05+U7ns9r6jqGxTA1mlSOpJdvtI36qf3x2KClR+jNyZbFooO96Lzo9dO9lFyynpQwKekcJWAasEyyfYHQe+QIL3qXtd/7kh4m+TFx7mUTRHH5p6zOlgePv0rAZ+27rk7gNdUkK9qrZSRBfxG2U1JKjp438p7O9/Eu8HwPLf4VGJ292RGFIIFA3met0BdBgrNpeIkH2MdgBHbtohtgUVeAq/cbvazT0B8Et3QRZls/lS4yr+ucv7vWK0CAwEAAaOBjDCBiTAfBgNVHSMEGDAWgBRLfi48SY5ScXg/G1as7ssSVoo0zDBBBggrBgEFBQcBAQQ1MDMwMQYIKwYBBQUHMAGGJWh0dHA6Ly9wa2kxLmV4YW1wbGUuY29tOjIwMDgwL2NhL29jc3AwDgYDVR0PAQH/BAQDAgTwMBMGA1UdJQQMMAoGCCsGAQUFBwMCMA0GCSqGSIb3DQEBDQUAA4IBAQBzP7og2r6J/XyyHotPJBy3W28vljAdmOnefoVh2+/wmwsFFDkY1Y2OAk0SHfudqGG2ZtgoyoxaCtOBvHy2oA2Bk9iZbs8Unn4i3RpKjMkG/9P24xK6oPIE3mYjgT5tLi460ERNBPb5iY4FRYXOBpJax9VofoeiqMRxUqDjtfa3AbFcRFyw9OiHB0TC4JPy6wAN8lYBVk2TsBAxuIuqRWKQd3x7Vv47SY4troSr68vgXipdp5bJYNfL0zgLxTNptQXcj6VrZZY4sEXFhn1jZfpIEHK/mYiixjUD2vzVSf6++V3d85JjhR7xMu/8AqBe5tcsAsxudsX/jhRW1BOfbgKq
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINE: SessionContextInterceptor: CAInfoResource.getInfo()
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINE: SessionContextInterceptor: Not authenticated.
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINE: AuthMethodInterceptor: CAInfoResource.getInfo()
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINE: AuthMethodInterceptor: mapping: default
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINE: AuthMethodInterceptor: required auth methods: [*]
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINE: AuthMethodInterceptor: anonymous access allowed
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINE: ACLInterceptor: CAInfoResource.getInfo()
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINE: ACLInterceptor.filter: no authorization required
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINE: ACLInterceptor: No ACL mapping; authz not required.
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINE: SignedAuditLogger: event AUTHZ
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Getting pidDir=/var/run/pki/tomcat
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Getting pidDir=/var/run/pki/tomcat
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINE: MessageFormatInterceptor: CAInfoResource.getInfo()
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINE: MessageFormatInterceptor: accept: [application/json]
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINE: MessageFormatInterceptor: response format: application/json
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINE: CAInfoService.getInfo(): session: 52107A4D01817426EF8E24024524478E
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Property processor.kraconnector.profileId not found
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Getting processor.kraconnector.profileId=
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Property processor.kraconnector.authzResourceName not found
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Getting processor.kraconnector.authzResourceName=
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Property processor.kraconnector.authMgr not found
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Getting processor.kraconnector.authMgr=
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Property processor.kraconnector.getClientCert not found
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Getting processor.kraconnector.getClientCert=
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Property processor.kraconnector.profileSubId not found
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Getting processor.kraconnector.profileSubId=
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Property processor.kraconnector.ACLinfo not found
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Getting processor.kraconnector.ACLinfo=
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Property processor.kraconnector.authzMgr not found
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Getting processor.kraconnector.authzMgr=
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Getting authz.sourceType=ldap
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Getting authz.sourceType=ldap
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINE: ServletUtils: according to ccMode, authorization for servlet: kraconnector is LDAP based, not XML {1}, use default authz mgr: {2}.
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Getting ca.connector.KRA.host=pki1.example.com
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Getting ca.connector.KRA.port=21443
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Getting ca.connector.KRA.enable=true
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Getting ca.connector.KRA.local=false
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Getting ca.connector.KRA.timeout=30
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Getting ca.connector.KRA.uri=/kra/agent/kra/connector
2021-07-15 10:01:17 [https-jsse-nio-20443-exec-24] FINEST: Getting ca.connector.KRA.transportCert=MIIDzjCCAragAwIBAgIBEjANBgkqhkiG9w0BAQ0FADBhMSUwIwYDVQQKDBx0b3BvbG9neS0wM19Gb29iYXJtYXN0ZXIub3JnMRcwFQYDVQQLDA50b3BvbG9neS0wMy1DQTEfMB0GA1UEAwwWQ0EgU2lnbmluZyBDZXJ0aWZpY2F0ZTAeFw0yMTA3MTUwNzA1NTFaFw0yMzA3MDUwNzA1NTFaMGUxJTAjBgNVBAoUHHRvcG9sb2d5LTAzX0Zvb2Jhcm1hc3Rlci5vcmcxGDAWBgNVBAsTD3RvcG9sb2d5LTAzLUtSQTEiMCAGA1UEAxMZRFJNIFRyYW5zcG9ydCBDZXJ0aWZpY2F0ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKmSskoGKHEBVzy6tA0+t2LGOqEh/ZcMxLlhPCg9VpNfxAVx/W6ATcvWR6F1dkr1SYXFpHd5WwWp6i/7sjRoAmLqtqQHNP9Z05+U7ns9r6jqGxTA1mlSOpJdvtI36qf3x2KClR+jNyZbFooO96Lzo9dO9lFyynpQwKekcJWAasEyyfYHQe+QIL3qXtd/7kh4m+TFx7mUTRHH5p6zOlgePv0rAZ+27rk7gNdUkK9qrZSRBfxG2U1JKjp438p7O9/Eu8HwPLf4VGJ292RGFIIFA3met0BdBgrNpeIkH2MdgBHbtohtgUVeAq/cbvazT0B8Et3QRZls/lS4yr+ucv7vWK0CAwEAAaOBjDCBiTAfBgNVHSMEGDAWgBRLfi48SY5ScXg/G1as7ssSVoo0zDBBBggrBgEFBQcBAQQ1MDMwMQYIKwYBBQUHMAGGJWh0dHA6Ly9wa2kxLmV4YW1wbGUuY29tOjIwMDgwL2NhL29jc3AwDgYDVR0PAQH/BAQDAgTwMBMGA1UdJQQMMAoGCCsGAQUFBwMCMA0GCSqGSIb3DQEBDQUAA4IBAQBzP7og2r6J/XyyHotPJBy3W28vljAdmOnefoVh2+/wmwsFFDkY1Y2OAk0SHfudqGG2ZtgoyoxaCtOBvHy2oA2Bk9iZbs8Unn4i3RpKjMkG/9P24xK6oPIE3mYjgT5tLi460ERNBPb5iY4FRYXOBpJax9VofoeiqMRxUqDjtfa3AbFcRFyw9OiHB0TC4JPy6wAN8lYBVk2TsBAxuIuqRWKQd3x7Vv47SY4troSr68vgXipdp5bJYNfL0zgLxTNptQXcj6VrZZY4sEXFhn1jZfpIEHK/mYiixjUD2vzVSf6++V3d85JjhR7xMu/8AqBe5tcsAsxudsX/jhRW1BOfbgKq
2021-07-15 10:01:21 [/var/lib/pki/topology-03-CA/logs/ca/signedAudit/ca_audit.flush-8] FINEST: Getting pidDir=/var/run/pki/tomcat
2021-07-15 10:01:21 [/var/lib/pki/topology-03-CA/logs/ca/signedAudit/ca_audit.flush-8] FINEST: Getting pidDir=/var/run/pki/tomcat

No KRA debug log found related to crmf request.

**Comment by ckelleyRH** [comment]
Closing as this is working on `master`
```
pki -c SECret.123 -u caadmin client-cert-request "CN=foo1" --algorithm rsa --length 2048 --profile caOtherCert --type crmf
Enter Password: 
WARNING: BAD_CERT_DOMAIN encountered on 'CN=localhost.localdomain,OU=pki-tomcat,O=EXAMPLE' indicates a common-name mismatch
  Request ID: 0xd9ef08f6480f2d8f48bb35e17b05775c
  Type: enrollment
  Request Status: pending
  Operation Result: success
```
