### ISSUE TITLE
ipa-server-install failure at pkispawn -s CA -f /tmp/tmpabc1234

### ISSUE THREAD

**Issue by wolf-allywilson** [dogtagpki/pki#3664]
Trying to install ipa-server and it fails at:

> Configuring certificate server (pki-tomcatd). Estimated time: 3 minutes
>   [1/30]: configuring certificate server instance

enabled debug, attached log file.
[install.log](https://github.com/dogtagpki/pki/files/6847553/install.log)

Contents of /var/log/pki/pki-tomcat/localhost.2021-07-20.log just repeats this:

> SEVERE: Servlet.service() for servlet [caGetStatus] in context with path [/ca] threw exception
> java.io.IOException: CS server is not ready to serve.
> 	at com.netscape.cms.servlet.base.CMSServlet.service(CMSServlet.java:425)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
> 	at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:288)
> 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:285)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
> 	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:320)
> 	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:175)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:297)
> 	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
> 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)
> 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
> 	at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:288)
> 	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:285)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
> 	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:320)
> 	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:260)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:237)
> 	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:55)
> 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:191)
> 	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:187)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:186)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:498)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
> 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
> 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
> 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
> 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.lang.Thread.run(Thread.java:748)

Contents of /var/log/pki/pki-tomcat/localhost_access_log.2021-07-20.txt just repeats this (once a second):

> 172.28.40.124 - - [20/Jul/2021:10:31:22 +0000] "GET /ca/admin/ca/getStatus HTTP/1.1" 500 2767
> 172.28.40.124 - - [20/Jul/2021:10:31:23 +0000] "GET /ca/admin/ca/getStatus HTTP/1.1" 500 2767
> 172.28.40.124 - - [20/Jul/2021:10:31:24 +0000] "GET /ca/admin/ca/getStatus HTTP/1.1" 500 2767

Tried changing the timeout parameter to 300 seconds, did nothing. 

selinux is disabled, no firewall.

Server does have 2 IP addresses, tried specifying one with --ip-address did nothing different.

This is on a Amazon Linux 2 amd64 instance, but happens on arm64 instance as well.

> Linux dir.aw.sum 4.14.238-182.421.amzn2.x86_64 #1 SMP Mon Jul 12 21:54:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```
ipa-server-install --version
```

> 4.6.8

**Comment by wolf-allywilson** [comment]
I tried to work around this thinking it was the CA creation part that was the problem by using an external CA, but it still fails at the same step when passing it the external cert and chain.
