### ISSUE TITLE
ACME enrollment fails with "Unsupported JWS algorithm: ES256"

### ISSUE THREAD

**Issue by dino2gnt** [dogtagpki/pki#3729]
Vanilla Fedora 34 with: 
```
[root@ca ~]# rpm -qa | grep pki-
pki-symkey-10.10.6-1.fc34.x86_64
dogtag-pki-console-theme-10.10.6-1.fc34.noarch
python3-pki-10.10.6-1.fc34.noarch
pki-base-10.10.6-1.fc34.noarch
pki-base-java-10.10.6-1.fc34.noarch
pki-tools-10.10.6-1.fc34.x86_64
pki-server-10.10.6-1.fc34.noarch
pki-acme-10.10.6-1.fc34.noarch
pki-ca-10.10.6-1.fc34.noarch
pki-kra-10.10.6-1.fc34.noarch
pki-ocsp-10.10.6-1.fc34.noarch
pki-tks-10.10.6-1.fc34.noarch
pki-tps-10.10.6-1.fc34.x86_64
pki-console-10.10.6-1.fc34.noarch
dogtag-pki-server-theme-10.10.6-1.fc34.noarch
```

Trying to set up a CA and ACME directory for my lab environment and running into this exception when attempting to enroll a certificate with ACME:

```
2021-08-28 09:10:39 [https-jsse-nio-8443-exec-4] INFO: Directory:
{"newNonce":"https://ca.mydomain.tld:8443/acme/new-nonce","newAccount":"https://ca.mydomain.tld:8443/acme/new-account","newOrder":"https://ca.mydomain.tld:8443/acme/new-order","revokeCert":"https://ca.mydomain.tld:8443/acme/revoke-cert","meta":{"termsOfService":"https://www.example.com/acme/tos.pdf","website":"https://ca.mydomain.tld:8443","caaIdentities":["example.com"],"externalAccountRequired":false}}
2021-08-28 09:10:43 [https-jsse-nio-8443-exec-6] INFO: LDAP: search ou=config,dc=acme,dc=mydomain,dc=tld
2021-08-28 09:10:43 [https-jsse-nio-8443-exec-6] INFO: Creating nonce
2021-08-28 09:10:43 [https-jsse-nio-8443-exec-6] INFO: Created nonce: {"id":"0uZw3HdKBSgJoAbxaPU1og","expires":"2021-08-28T09:40:43-05:00"}
2021-08-28 09:10:43 [https-jsse-nio-8443-exec-7] INFO: LDAP: search ou=config,dc=acme,dc=mydomain,dc=tld
2021-08-28 09:10:43 [https-jsse-nio-8443-exec-7] INFO: Creating new account
2021-08-28 09:10:43 [https-jsse-nio-8443-exec-7] INFO: Header: {"alg":"ES256","url":"https://ca.mydomain.tld:8443/acme/new-account","nonce":"0uZw3HdKBSgJoAbxaPU1og","jwk":{"crv":"P-256","kty":"EC","x":"t9OohvtUnQwViFBzg3yy8gE5ZkKhFzEUKxasDQIogOk","y":"CgiwiSRwRC983m9BpomUgDVkd9vErZAoC9gpVwPHWJQ"}}
2021-08-28 09:10:43 [https-jsse-nio-8443-exec-7] INFO: Valid nonce: 0uZw3HdKBSgJoAbxaPU1og
2021-08-28 09:10:43 [https-jsse-nio-8443-exec-7] INFO: JWK: {"kty":"EC"}
2021-08-28 09:10:43 [https-jsse-nio-8443-exec-7] SEVERE: Servlet.service() for servlet [ACME] in context with path [/acme] threw exception
org.jboss.resteasy.spi.UnhandledException: java.lang.Exception: Unsupported JWS algorithm: ES256
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:78)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:222)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:179)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:422)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:213)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
        at jdk.internal.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:550)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:170)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:221)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at jdk.internal.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:550)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:187)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at com.netscape.cms.tomcat.ExternalAuthenticationValve.invoke(ExternalAuthenticationValve.java:82)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.Exception: Unsupported JWS algorithm: ES256
        at org.dogtagpki.acme.server.ACMEEngine.validateJWS(ACMEEngine.java:679)
        at org.dogtagpki.acme.server.ACMENewAccountService.createNewAccount(ACMENewAccountService.java:55)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:406)
        ... 48 more
```

Not sure where I've gone wrong. Extensive googling was not enlightening.  No similar issues on Github.  I can't be the only one?

**Comment by dino2gnt** [comment]
PR: https://github.com/dogtagpki/pki/pull/3730

**Comment by mholt** [comment]
Hi, sorry to comment on an old issue, but Caddy users are getting this error, and the ACME server is in violation of RFC 8555 if it does not support ES256:

> An ACME server MUST implement the "ES256" signature algorithm
>   [[RFC7518](https://datatracker.ietf.org/doc/html/rfc7518)] and SHOULD implement the "EdDSA" signature algorithm using
>   the "Ed25519" variant (indicated by "crv") [[RFC8037](https://datatracker.ietf.org/doc/html/rfc8037)].

So, I believe the PR #3730 that asks clients to fall back to a less efficient algorithm is not the correct fix.

@dino2gnt Would you consider implementing ES256 to be compliant with the ACME spec?

**Comment by edewata** [comment]
@mholt Hi, would you mind creating a new ticket for that? We'll discuss it with the team. Thanks!

**Comment by mholt** [comment]
Absolutely. Cheers! See https://github.com/dogtagpki/pki/issues/4638
