### ISSUE TITLE
add a test on a null attrs pointer in  DirBasedAuthentication.java

### ISSUE THREAD

**Issue by msauton** [dogtagpki/pki#3932]
add a test on a null attrs pointer before a for loop

https://github.com/dogtagpki/pki/blob/master/base/server/src/main/java/com/netscape/cms/authentication/DirBasedAuthentication.java#L611

base/server/src/main/java/com/netscape/cms/authentication/DirBasedAuthentication.java
line 611
               String[] attrs = getLdapAttrs();
               logger.info("DirBasedAuthentication: - attributes:");
                for (String attr : attrs) {                        <<<<<<<<<<<<  LINE 611
                    logger.info("DirBasedAuthentication:   - " + attr);
                }

it may be possible no LDAP attributes are identified, and the for loop can end up into a Java NULL pointer exception:

2022-03-10 18:10:53 [https-jsse-nio-8443-exec-1] INFO: DirBasedAuthentication: Searching for uid=guest1,ou=users,dc=example,dc=test
2022-03-10 18:10:53 [https-jsse-nio-8443-exec-1] INFO: DirBasedAuthentication: - attributes:
2022-03-10 18:10:53 [https-jsse-nio-8443-exec-1] SEVERE: ProfileSubmitServlet: error in processing request: null
java.lang.NullPointerException
        at com.netscape.cms.authentication.DirBasedAuthentication.formCertInfo(DirBasedAuthentication.java:611) <<<<<<<<<<<<<<<<
        at com.netscape.cms.authentication.DirBasedAuthentication.authenticate(DirBasedAuthentication.java:479)
        at com.netscape.cms.servlet.processors.CAProcessor.authenticate(CAProcessor.java:438)
base/server/src/main/java/com/netscape/cms/authentication/DirBasedAuthentication.java

**Comment by ckelleyRH** [comment]
@msauton apparently you are not a member of dogtagpki - I tried to add you as a PR reviewer. Do you want to be extended this permission or are you fine as you are?

**Comment by msauton** [comment]
sure, yes
Marc S
