### ISSUE TITLE
pypi package not able to be installed due to python-nss dependency

### ISSUE THREAD

**Issue by veruu** [dogtagpki/pki#4137]
Currently the package on pypi has version 10.7.4.1 which still contains has required dependency on python-nss. That package is pretty much unmaintained these days, and fails to build from source (has no wheels) due to renames of structures in nss-devel. This makes dogtag-pki impossible to install from pypi.

Reproducible on Fedora rawhide which currently has python3.11:

```
# pip install dogtag-pki
Collecting dogtag-pki
  Downloading dogtag_pki-10.7.4.1-py2.py3-none-any.whl (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.3/90.3 kB 1.7 MB/s eta 0:00:00
Collecting python-nss
  Downloading python-nss-1.0.1.tar.bz2 (222 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 222.1/222.1 kB 4.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-psbirace/python-nss_c1c7879b028346669f1151d532a79829/setup.py", line 409, in <module>
          sys.exit(main(sys.argv))
                   ^^^^^^^^^^^^^^
        File "/tmp/pip-install-psbirace/python-nss_c1c7879b028346669f1151d532a79829/setup.py", line 333, in main
          nss_include_dir  = find_include_dir(['nss3', 'nss'],   ['nss.h',  'pk11pub.h'], include_roots=include_roots)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-psbirace/python-nss_c1c7879b028346669f1151d532a79829/setup.py", line 94, in find_include_dir
          raise ValueError("unable to locate include directory containing header files %s" % include_files)
      ValueError: unable to locate include directory containing header files ['nss.h', 'pk11pub.h']
```

After installing nss-devel to provide the header files (nss-devel-3.81.0-1.fc37.x86_64.rpm, nspr-devel-4.34.0-3.fc37.x86_64.rpm):

```
# pip install dogtag-pki
Collecting dogtag-pki
  Using cached dogtag_pki-10.7.4.1-py2.py3-none-any.whl (90 kB)
Collecting python-nss
  Using cached python-nss-1.0.1.tar.bz2 (222 kB)
  Preparing metadata (setup.py) ... done
Collecting requests
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting cryptography
  Using cached cryptography-37.0.4-cp36-abi3-manylinux_2_24_x86_64.whl (4.1 MB)
Collecting cffi>=1.12
  Using cached cffi-1.15.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (462 kB)
Collecting charset-normalizer<3,>=2
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.6.15-py3-none-any.whl (160 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Building wheels for collected packages: python-nss
  Building wheel for python-nss (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [88 lines of output]
      /usr/lib/python3.11/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'dist-dir' will not be supported in future versions. Please use the underscore name 'dist_dir' instead
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/nss
      copying src/__init__.py -> build/lib.linux-x86_64-cpython-311/nss
      running build_ext
      building 'nss.error' extension
      creating build/temp.linux-x86_64-cpython-311
      creating build/temp.linux-x86_64-cpython-311/src
      gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/nss3 -I/usr/include/nspr4 -I/usr/include/python3.11 -c src/py_nspr_error.c -o build/temp.linux-x86_64-cpython-311/src/py_nspr_error.o
      gcc -shared -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -Wl,--build-id=sha1 -g -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -Wl,--build-id=sha1 -g build/temp.linux-x86_64-cpython-311/src/py_nspr_error.o -L/usr/lib64 -lnspr4 -o build/lib.linux-x86_64-cpython-311/nss/error.cpython-311-x86_64-linux-gnu.so
      building 'nss.io' extension
      gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/nss3 -I/usr/include/nspr4 -I/usr/include/python3.11 -c src/py_nspr_io.c -o build/temp.linux-x86_64-cpython-311/src/py_nspr_io.o
      src/py_nspr_io.c: In function ‘Socket_poll’:
      src/py_nspr_io.c:3159:19: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘Py_ssize_t’ {aka ‘long int’} [-Wsign-compare]
       3159 |     for (i = 0; i < num_descs; i++) {
            |                   ^
      src/py_nspr_io.c:3201:19: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘Py_ssize_t’ {aka ‘long int’} [-Wsign-compare]
       3201 |     for (i = 0; i < num_descs; i++) {
            |                   ^
      gcc -shared -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -Wl,--build-id=sha1 -g -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -Wl,--build-id=sha1 -g build/temp.linux-x86_64-cpython-311/src/py_nspr_io.o -L/usr/lib64 -lnspr4 -o build/lib.linux-x86_64-cpython-311/nss/io.cpython-311-x86_64-linux-gnu.so
      building 'nss.nss' extension
      gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isrc -I/usr/include/nss3 -I/usr/include/nspr4 -I/usr/include/python3.11 -c src/py_nss.c -o build/temp.linux-x86_64-cpython-311/src/py_nss.o
      In file included from src/py_nss.h:22,
                       from src/py_nss.c:341:
      /usr/include/nss3/key.h:9:9: note: ‘#pragma message: key.h is deprecated. Please include keyhi.h instead.’
          9 | #pragma message("key.h is deprecated. Please include keyhi.h instead.")
            |         ^~~~~~~
      src/py_nss.h:126:3: error: conflicting types for ‘RSAPublicKey’; have ‘struct <anonymous>’
        126 | } RSAPublicKey;
            |   ^~~~~~~~~~~~
      In file included from /usr/include/nss3/pk11hpke.h:8,
                       from /usr/include/nss3/pk11pub.h:12,
                       from src/py_nss.h:23:
      /usr/include/nss3/blapit.h:283:32: note: previous declaration of ‘RSAPublicKey’ with type ‘RSAPublicKey’ {aka ‘struct RSAPublicKeyStr’}
        283 | typedef struct RSAPublicKeyStr RSAPublicKey;
            |                                ^~~~~~~~~~~~
      src/py_nss.h:136:3: error: conflicting types for ‘DSAPublicKey’; have ‘struct <anonymous>’
        136 | } DSAPublicKey;
            |   ^~~~~~~~~~~~
      /usr/include/nss3/blapit.h:325:32: note: previous declaration of ‘DSAPublicKey’ with type ‘DSAPublicKey’ {aka ‘struct DSAPublicKeyStr’}
        325 | typedef struct DSAPublicKeyStr DSAPublicKey;
            |                                ^~~~~~~~~~~~
      In file included from src/py_nss.c:339:
      src/py_nss.c: In function ‘SECItem_to_base64’:
      src/py_nspr_common.h:256:23: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘long int’ [-Wsign-compare]
        256 | #define MIN(a,b) ((a) < (b) ? (a) : (b))
            |                       ^
      src/py_nss.c:1832:24: note: in expansion of macro ‘MIN’
       1832 |             line_len = MIN(chars_per_line, src_end - src);
            |                        ^~~
      src/py_nspr_common.h:256:37: warning: operand of ‘?:’ changes signedness from ‘long int’ to ‘size_t’ {aka ‘long unsigned int’} due to unsignedness of other operand [-Wsign-compare]
        256 | #define MIN(a,b) ((a) < (b) ? (a) : (b))
            |                                     ^~~
      src/py_nss.c:1832:24: note: in expansion of macro ‘MIN’
       1832 |             line_len = MIN(chars_per_line, src_end - src);
            |                        ^~~
      src/py_nss.c: In function ‘CERTAVA_value_to_pystr’:
      src/py_nss.c:4818:41: warning: comparison of integer expressions of different signedness: ‘SECOidTag’ and ‘int’ [-Wsign-compare]
       4818 |     if ((oid_tag = CERT_GetAVATag(ava)) != -1) {
            |                                         ^~
      src/py_nss.c: In function ‘CERTRDN_to_pystr’:
      src/py_nss.c:4882:45: warning: comparison of integer expressions of different signedness: ‘SECOidTag’ and ‘int’ [-Wsign-compare]
       4882 |         if ((oid_tag = CERT_GetAVATag(ava)) != -1) {
            |                                             ^~
      src/py_nss.c: In function ‘Certificate_get_extension’:
      src/py_nss.c:10192:53: warning: comparison of integer expressions of different signedness: ‘SECOidTag’ and ‘int’ [-Wsign-compare]
      10192 |     if ((oid_tag = get_oid_tag_from_object(py_oid)) == -1) {
            |                                                     ^~
      src/py_nss.c: In function ‘pk11_create_pbev2_algorithm_id’:
      src/py_nss.c:23446:65: warning: comparison of integer expressions of different signedness: ‘SECOidTag’ and ‘int’ [-Wsign-compare]
      23446 |         if ((pbe_alg_tag = get_oid_tag_from_object(py_pbe_alg)) == -1) {
            |                                                                 ^~
      src/py_nss.c:23453:71: warning: comparison of integer expressions of different signedness: ‘SECOidTag’ and ‘int’ [-Wsign-compare]
      23453 |         if ((cipher_alg_tag = get_oid_tag_from_object(py_cipher_alg)) == -1) {
            |                                                                       ^~
      src/py_nss.c:23460:65: warning: comparison of integer expressions of different signedness: ‘SECOidTag’ and ‘int’ [-Wsign-compare]
      23460 |         if ((prf_alg_tag = get_oid_tag_from_object(py_prf_alg)) == -1) {
            |                                                                 ^~
      src/py_nss.c: In function ‘pkcs12_enable_all_ciphers’:
      src/py_nss.c:24381:19: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
      24381 |     for (i = 0; i < sizeof(all_ciphers)/sizeof(all_ciphers[0]); i++) {
            |                   ^
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-nss
```

Given that the dependency was completely removed via https://github.com/dogtagpki/pki/commit/077c137c5b36906656da0c14ccdc2bc56a693d1e the solution seems to be to publish a pypi package with the newest 11.0.0 release

ccing @tiran who suggested to open the issue here :hugs:

**Comment by veruu** [comment]
Also linking a potentially related https://github.com/dogtagpki/pki/issues/3230

**Comment by tiran** [comment]
Problem: The `setup.py` file for client libraries is outdated and no longer works correctly. It used to detect the version from `pki.spec` file. This needs to be fixed first or Dogtag needs to use a different approach.

```
$ cd base/common/python
$ python3 setup.py sdist
$ ls dist/
dogtag-pki-0.0.0.tar.gz
```

**Comment by tiran** [comment]
To unblock Veronika, I have release https://pypi.org/project/dogtag-pki/11.2.1/ from the v11.2.1 tag with a modified `setup.py`.

```
 setup(
     author='Dogtag Certificate System Team',
     author_email='devel@lists.dogtagpki.org',
     name='dogtag-pki',
-    version=VERSION,
+    version="11.2.1",
     description='Client library for Dogtag Certificate System',
     long_description="""\
 This package contains the REST client for Dogtag PKI.
@@ -125,14 +59,17 @@ and set up in less than an hour.""",
     url='https://www.dogtagpki.org',
     packages=['pki', 'pki.cli'],
     install_requires=['requests', 'six', 'cryptography'],
-    cmdclass={'version_info': VersionInfo},
     classifiers=[
         'Development Status :: 5 - Production/Stable',
         'Environment :: Web Environment',
         'Intended Audience :: System Administrators',
         'Operating System :: OS Independent',
-        'Programming Language :: Python :: 2.7',
-        'Programming Language :: Python :: 3.4',
+        'Programming Language :: Python :: 3.6',
+        'Programming Language :: Python :: 3.7',
+        'Programming Language :: Python :: 3.8',
+        'Programming Language :: Python :: 3.9',
+        'Programming Language :: Python :: 3.10',
+        'Programming Language :: Python :: 3.11',
         'License :: OSI Approved :: GNU Lesser General Public License ' +
             'v3 or later (LGPLv3+)',
         'Topic :: Security :: Cryptography',
```

```
$ python3 -m build
$ twine upload dist/dogtag*
```
