### ISSUE TITLE
KRA Transport Certificate needs to be imported into the CA nssdb f

### ISSUE THREAD

**Issue by BorjanEch0** [dogtagpki/pki#4277]
Hello all, i am getting this error on trying to enroll certificate from web with server side generation.
ca and kra are sharing an instance, kra transport cert is enrolled in nssdb and server dbs and specified in the CS.cfg and everywhere its the same certificate but still no luck.
also verified pki -c Secret.123 -n caadmin ca-kraconnector-show connector is configured correctly.
This is present in the debug log.
`2022-12-26 00:44:15 [https-jsse-nio-8443-exec-3] INFO: AAclAuthz: Granting read permission for certServer.ee.profile
2022-12-26 00:44:24 [https-jsse-nio-8443-exec-4] INFO: EnrollProfile: Creating ernrollment request 18
2022-12-26 00:44:24 [https-jsse-nio-8443-exec-4] INFO: UserSubjectNameDefault: Subject: UID=d,E=d,CN=d,OU=d,OU=d,OU=d,OU=d,O=d,C=d
2022-12-26 00:44:24 [https-jsse-nio-8443-exec-4] SEVERE: ProfileSubmitServlet: error in processing request: KRA Transport Certificate needs to be imported into the CA nssdb for Server-Side Kegen Enrollment
KRA Transport Certificate needs to be imported into the CA nssdb for Server-Side Kegen Enrollment
        at com.netscape.cms.profile.def.ServerKeygenUserKeyDefault.populate(ServerKeygenUserKeyDefault.java:495)
        at com.netscape.cms.profile.def.EnrollDefault.populate(EnrollDefault.java:232)
        at com.netscape.cms.profile.common.Profile.populate(Profile.java:1271)
        at com.netscape.cms.profile.common.EnrollProfile.populate(EnrollProfile.java:2668)
        at com.netscape.cms.servlet.cert.CertProcessor.populateRequests(CertProcessor.java:392)
        at com.netscape.cms.servlet.cert.EnrollmentProcessor.processEnrollment(EnrollmentProcessor.java:189)
        at com.netscape.cms.servlet.cert.EnrollmentProcessor.processEnrollment(EnrollmentProcessor.java:97)
        at com.netscape.cms.servlet.profile.ProfileSubmitServlet.processEnrollment(ProfileSubmitServlet.java:279)
        at com.netscape.cms.servlet.profile.ProfileSubmitServlet.process(ProfileSubmitServlet.java:132)
        at com.netscape.cms.servlet.base.CMSServlet.service(CMSServlet.java:488)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
        at jdk.internal.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:170)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:221)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at jdk.internal.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:187)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at com.netscape.cms.tomcat.ExternalAuthenticationValve.invoke(ExternalAuthenticationValve.java:83)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:833)
`

any help is very appreciated.

Sorry, your request is not submitted. The reason is "KRA Transport Certificate needs to be imported into the CA nssdb for Server-Side Kegen Enrollment".

**Comment by BorjanEch0** [comment]
To anyone else struggling:
Issue was: By default the file /var/lib/pki/pki-tomcat/ca/conf/CS.cfg does not contain the line ca.connector.KRA.transportCertNickname=transportCert cert-pki-tomcat KRA pkispawn should do this automatically!
