### ISSUE TITLE
Don't assume user's temp directory is traversable

### ISSUE THREAD

**Issue by stanislavlevin** [dogtagpki/pki#4475]
`pkispawn` fails as of dogtag-pki 11.3.0 with:

```
java.io.FileNotFoundException: /tmp/.private/root/tmpect0fnzq/password.txt (Permission denied)
        at java.base/java.io.FileInputStream.open0(Native Method)                
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)      
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)    
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)    
        at java.base/java.io.FileReader.<init>(FileReader.java:60)               
        at com.netscape.cmstools.cli.MainCLI.loadPassword(MainCLI.java:241)      
        at com.netscape.cmstools.cli.MainCLI.parseOptions(MainCLI.java:416)      
        at com.netscape.cmstools.cli.MainCLI.execute(MainCLI.java:647)           
        at com.netscape.cmstools.cli.MainCLI.main(MainCLI.java:698)              
ERROR: CalledProcessError: Command '['runuser', '-u', 'pkiuser', '--', 'pki', '-d', '/etc/pki/pki-tomcat/alias', '-C', '/tmp/.private/root/tmpect0fnzq/password.txt', 'nss-cert-request', '--subject', 'cn=dc.ipa.test,o=2023-06-09 11:52:08', '--csr', '/tmp/.private/root/tmp0o_hypwu/sslserver.csr', '--key-type', 'RSA', '--key-size', '2048', '--hash', 'SHA256']' returned non-zero exit status 255.
  File "/usr/lib64/python3/site-packages/pki/server/pkispawn.py", line 588, in main
    scriptlet.spawn(deployer)                                                    
  File "/usr/lib64/python3/site-packages/pki/server/deployment/scriptlets/configuration.py", line 222, in spawn
    deployer.create_temp_sslserver_cert(instance)                                
  File "/usr/lib64/python3/site-packages/pki/server/deployment/__init__.py", line 2013, in create_temp_sslserver_cert
    nssdb.create_request(                                                        
  File "/usr/lib64/python3/site-packages/pki/nssdb.py", line 914, in create_request
    self.__create_request(                                                       
  File "/usr/lib64/python3/site-packages/pki/nssdb.py", line 1508, in __create_request
    self.run(cmd, check=True, runas=True)                                        
  File "/usr/lib64/python3/site-packages/pki/nssdb.py", line 268, in run         
    result = subprocess.run(                                                     
             ^^^^^^^^^^^^^^^                                                     
  File "/usr/lib64/python3.11/subprocess.py", line 569, in run                   
    raise CalledProcessError(retcode, process.args,                              
                                                                                 
                                                                                 
Installation failed: Command failed: runuser -u pkiuser -- pki -d /etc/pki/pki-tomcat/alias -C /tmp/.private/root/tmpect0fnzq/password.txt nss-cert-request --subject cn=dc.ipa.test,o=2023-06-09 11:52:08 --csr /tmp/.private/root/tmp0o_hypwu/sslserver.csr --key-type RSA --key-size 2048 --hash SHA256
```

We use `pam_mktemp` in ALTLinux by default (https://github.com/openwall/pam_mktemp), that implies per user temp directories like `/tmp/.private/USER`. Breaking change (c32df519038af529cb93fef8b83603f411a25439) assumes traversable temp directory of any user.

How to reproduce:
- prepare temp directory with corresponding permissions:
  ```console
  [root@dc ~]# ls -la /tmp/.private/root                                                                                                                
  drwx-----T 2 root root 40 Jun  7 14:01 .                                         
  drwxr-xr-x 4 root root 80 Jun  8 09:52 .. 
  ```
- set `TMPDIR` env variable                                   
  ```console                                           
  [root@dc ~]# export TMPDIR=/tmp/.private/root 
  ```
- run `pkispawn`                                   
  ```console                                                                     
  [root@dc /]# pkispawn
  ```

**Comment by stanislavlevin** [comment]
CC @rcritten

**Comment by stanislavlevin** [comment]
This should help.

**Comment by rcritten** [comment]
This should be backported to 11.3 and 11.4. I can open those PRs as well if desired.

**Comment by stanislavlevin** [comment]
Thank you!

**Comment by stanislavlevin** [comment]
I tested the patch today, unfortunately it didn't fix my issue completely.
<details>
<summary>An example of error (spoiler) </summary>

```
java.nio.file.AccessDeniedException: /tmp/.private/root/tmps57i6g40/sslserver.csr
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
        at java.base/java.nio.file.Files.write(Files.java:3512)
        at com.netscape.cmstools.nss.NSSCertRequestCLI.execute(NSSCertRequestCLI.java:181)
        at org.dogtagpki.cli.CommandCLI.execute(CommandCLI.java:58)
        at org.dogtagpki.cli.CLI.execute(CLI.java:353)
        at org.dogtagpki.cli.CLI.execute(CLI.java:353)
        at org.dogtagpki.cli.CLI.execute(CLI.java:353)
        at com.netscape.cmstools.cli.MainCLI.execute(MainCLI.java:659)
        at com.netscape.cmstools.cli.MainCLI.main(MainCLI.java:698)
ERROR: CalledProcessError: Command '['runuser', '-u', 'pkiuser', '--', 'pki', '-d', '/etc/pki/pki-tomcat/alias', '-C', '/tmp/tmpx05hn8yr/password.txt', 'nss-cert-request', '--subject', 'cn=ipa.example.test,o=2023-08-15 15:28:23', '--csr', '/tmp/.private/root/tmps57i6g40/sslserver.csr', '--key-type', 'RSA', '--key-size', '2048', '--hash', 'SHA256']' returned non-zero exit status 255.
  File "/usr/lib64/python3/site-packages/pki/server/pkispawn.py", line 588, in main
    scriptlet.spawn(deployer)
  File "/usr/lib64/python3/site-packages/pki/server/deployment/scriptlets/configuration.py", line 222, in spawn
    deployer.create_temp_sslserver_cert(instance)
  File "/usr/lib64/python3/site-packages/pki/server/deployment/__init__.py", line 2012, in create_temp_sslserver_cert
    nssdb.create_request(
  File "/usr/lib64/python3/site-packages/pki/nssdb.py", line 914, in create_request
    self.__create_request(
  File "/usr/lib64/python3/site-packages/pki/nssdb.py", line 1508, in __create_request
    self.run(cmd, check=True, runas=True)
  File "/usr/lib64/python3/site-packages/pki/nssdb.py", line 268, in run
    result = subprocess.run(
             ^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
```
</details>

I added at least
<details>
<summary>this change (spoiler) to get basic installation work</summary>

```diff
--- a/base/server/python/pki/server/deployment/__init__.py
+++ b/base/server/python/pki/server/deployment/__init__.py
@@ -1931,7 +1931,7 @@ class PKIDeployer:
 
             generic_exts = [generic_ext]
 
-        tmpdir = tempfile.mkdtemp()
+        tmpdir = tempfile.mkdtemp(dir='/tmp')
         try:
             csr_file = os.path.join(tmpdir, 'request.csr')
 
@@ -1973,7 +1973,7 @@ class PKIDeployer:
 
         instance.set_sslserver_cert_nickname(nickname)
 
-        tmpdir = tempfile.mkdtemp()
+        tmpdir = tempfile.mkdtemp(dir='/tmp')
         nssdb = instance.open_nssdb(
             user=self.mdict['pki_user'],
             group=self.mdict['pki_group']
```
</details>

But I'm concerned that `mkdtemp` (quite a few  of them in the code) may lead to such a problem.
