### ISSUE TITLE
Broken installation with IPA on f38 with pki from @pki/master

### ISSUE THREAD

**Issue by flo-renaud** [dogtagpki/pki#4621]
I am trying to install PKI from @pki/master on fedora38 and IPA server installation fails because of a missing java class.

Steps:
1. update all the packages with `dnf update -y`
2. enable the copr repo with `dnf copr enable -y @pki/master`
3. install ipa from master branch: `dnf copr enable -y @freeipa/freeipa-master-nightly; dnf install -y freeipa-server-dns`
4. configure the IPA server: `ipa-server-install --domain ipa.test --realm IPA.TEST --setup-dns --auto-forwarders -a Secret123 -p Secret123 -U`

The ipa-server-install command fails in the step configuring PKI server:
```
[...]
Done configuring ipa-custodia.
Configuring certificate server (pki-tomcatd). Estimated time: 3 minutes
  [1/30]: configuring certificate server instance
Failed to configure CA instance
See the installation logs and the following files/directories for more information:
  /var/log/pki/pki-tomcat
  [error] RuntimeError: CA configuration failed.
CA configuration failed.
The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
```

The file /var/log/pki/pki-tomcat/ca/debug.$DATE shows a ClassNotFoundException:
```
2023-11-27 10:21:31 [https-jsse-jss-nio-8443-exec-2] SEVERE: Servlet.service() for servlet [caGetStatus] in context with path [/ca] threw exception [com/fasterxml/jackson/core/exc/StreamConstraintsException] with root cause
java.lang.ClassNotFoundException: com.fasterxml.jackson.core.exc.StreamConstraintsException
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at com.fasterxml.jackson.databind.node.JsonNodeFactory.objectNode(JsonNodeFactory.java:353)
        at com.fasterxml.jackson.databind.ObjectMapper.createObjectNode(ObjectMapper.java:3411)
        at com.netscape.cmsutil.json.JSONObject.<init>(JSONObject.java:33)
        at com.netscape.cms.servlet.csadmin.GetStatus.process(GetStatus.java:82)
        at com.netscape.cms.servlet.base.CMSServlet.service(CMSServlet.java:502)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:222)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:250)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:142)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:207)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:137)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:136)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:222)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:584)
        at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:250)
        at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:202)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:176)
        at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:137)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:136)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
        at com.netscape.cms.tomcat.ExternalAuthenticationValve.invoke(ExternalAuthenticationValve.java:83)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:545)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

The class `com/fasterxml/jackson/core/exc/StreamConstraintsException` is provided by /usr/share/java/jackson-core.jar which is shipped with jackson-core 2.15 but not with jackson-core 2.14.

The same steps work on fedora 39.

Installed packages on fedora38:
```
# rpm -qa freeipa-server dogtag-pki-base jackson-core
dogtag-pki-base-11.5.0-0.1.alpha3.20231117204113UTC.560be6e5.fc38.noarch
jackson-core-2.14.2-1.fc38.noarch
freeipa-server-4.12.0.dev202311201347+git-0.fc38.x86_64
# rpm -qf /usr/share/java/jackson-core.jar 
jackson-core-2.14.2-1.fc38.noarch
#  jar tf /usr/share/java/jackson-core.jar | grep com/fasterxml/jackson/core/exc/StreamConstraintsException
# 
```
jackson-core 2.14 does not provide the class.

Installed packages on fedora39:
```
# rpm -qa freeipa-server dogtag-pki-base jackson-core
dogtag-pki-base-11.5.0-0.1.alpha3.20231127140649UTC.0753e8db.fc39.noarch
jackson-core-2.15.2-2.fc39.noarch
freeipa-server-4.12.0.dev202311201347+git-0.fc39.x86_64
# rpm -qf /usr/share/java/jackson-core.jar 
jackson-core-2.15.2-2.fc39.noarch
# jar tf /usr/share/java/jackson-core.jar | grep com/fasterxml/jackson/core/exc/StreamConstraintsException
com/fasterxml/jackson/core/exc/StreamConstraintsException.class
```
jackson-core 2.15 provides the class.

**Comment by edewata** [comment]
@fmarco76 FYI

**Comment by fmarco76** [comment]
@edewata @flo-renaud I am looking at this problem right now. There is a jackson update which is creating problem to F38 (and RHEL) but it works on F37 and F39. I will update ASAP

**Comment by fmarco76** [comment]
@flo-renaud could you test again the build of F38? It should work now. In my test jackson package in copr should be correct for all fedora versions.

**Comment by flo-renaud** [comment]
Tested with the following versions:
```
# rpm -qa freeipa-server dogtag-pki-base jackson-core
dogtag-pki-base-11.5.0-0.1.alpha3.20231128122431UTC.2ac7ae17.fc38.noarch
jackson-core-2.16.0-1.fc38.noarch
freeipa-server-4.12.0.dev202311271719+git-0.fc38.x86_64
```

It works now, thanks
