### ISSUE TITLE
ipa-cert-fix is failing with hsm using @pki/master copr repo

### ISSUE THREAD

**Issue by amore17** [dogtagpki/pki#4873]
With the PKI packages from @pki/master repository, the scenario ipa-cert-fix fails.

```
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557 INFO: Configuring LDAP connection for ACME
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557 ERROR: 'internaldb.ldapauth.authtype'
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557 Traceback (most recent call last):
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557   File "/usr/lib/python3.12/site-packages/pki/server/pkiserver.py", line 41, in <module>
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557     cli.execute(sys.argv)
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557   File "/usr/lib/python3.12/site-packages/pki/server/cli/__init__.py", line 144, in execute
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557     super().execute(args)
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557   File "/usr/lib/python3.12/site-packages/pki/cli/__init__.py", line 217, in execute
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557     module.execute(module_args)
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557   File "/usr/lib/python3.12/site-packages/pki/cli/__init__.py", line 217, in execute
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557     module.execute(module_args)
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557   File "/usr/lib/python3.12/site-packages/pki/server/cli/cert.py", line 1430, in execute
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557     ldap_password_authn(
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557   File "/usr/lib64/python3.12/contextlib.py", line 137, in __enter__
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557     return next(self.gen)
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557            ^^^^^^^^^^^^^^
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557   File "/usr/lib/python3.12/site-packages/pki/server/cli/cert.py", line 1615, in ldap_password_authn
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557     authtype = cfg['internaldb.ldapauth.authtype']
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557                ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557 KeyError: 'internaldb.ldapauth.authtype'
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557 
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557 Enter "yes" to proceed: Proceeding.
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557 ipapython.admintool: DEBUG:   File "/usr/lib/python3.12/site-packages/ipapython/admintool.py", line 180, in execute
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557     return_value = self.run()
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557                    ^^^^^^^^^^
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557   File "/usr/lib/python3.12/site-packages/ipaserver/install/ipa_cert_fix.py", line 152, in run
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557     run_cert_fix(certs, extra_certs)
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557   File "/usr/lib/python3.12/site-packages/ipaserver/install/ipa_cert_fix.py", line 375, in run_cert_fix
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557     ipautil.run(cmd, raiseonerr=True)
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557   File "/usr/lib/python3.12/site-packages/ipapython/ipautil.py", line 594, in run
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557     raise CalledProcessError(
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd72:transport.py:557 

```

**Comment by amore17** [comment]
[PKI log](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/1f0e2ab4-8429-11ef-afaa-fa163ef47834/test_integration-test_hsm.py-TestHSMcertFix-test_hsm_renew_expired_cert_on_master/master.ipa.test/var/log/pki/)

**Comment by flo-renaud** [comment]
The issue also happens without HSM: [report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/e98d9494-8f4d-11ef-90a7-fa163efee21d/report.html?sort=result)

**Comment by edewata** [comment]
@amore17 @flo-renaud hi, the issue should be fixed now. please try again with the latest COPR build. if it's still a problem please feel free to reopen. thanks!

**Comment by flo-renaud** [comment]
@edewata 
we see a different error now:
```
ipapython.ipautil: DEBUG: Starting external process
ipapython.ipautil: DEBUG: args=['pki-server', 'cert-fix', '--ldapi-socket', '/run/slapd-UFREEIPA-TEST.socket', '--agent-uid', 'ipara', '--cert', 'sslserver', '--cert', 'subsystem', '--cert', 'ca_ocsp_signing', '--cert', 'ca_audit_signing', '--extra-cert', '326927193689702498853940060656072272345', '--extra-cert', '40488042564141254294002070329107376970', '--extra-cert', '86013533104087455805498665371639067193', '--extra-cert', '86743368863325796666336266970492023132']
ipapython.ipautil: DEBUG: Process finished, return code=1
ipapython.ipautil: DEBUG: stdout=
ipapython.ipautil: DEBUG: stderr=SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
WARNING: No selftests configured in /var/lib/pki/pki-tomcat/conf/acme/CS.cfg (selftests.container.order.startup).
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
WARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1639: The PKIConnection parameter in AccountClient.__init__() has been deprecated. Provide PKIClient instead.
WARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1779: The PKIConnection parameter in CertClient.__init__() has been deprecated. Provide PKIClient instead.
WARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1639: The PKIConnection parameter in AccountClient.__init__() has been deprecated. Provide PKIClient instead.
WARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1779: The PKIConnection parameter in CertClient.__init__() has been deprecated. Provide PKIClient instead.
WARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1639: The PKIConnection parameter in AccountClient.__init__() has been deprecated. Provide PKIClient instead.
WARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1779: The PKIConnection parameter in CertClient.__init__() has been deprecated. Provide PKIClient instead.
WARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1639: The PKIConnection parameter in AccountClient.__init__() has been deprecated. Provide PKIClient instead.
WARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1779: The PKIConnection parameter in CertClient.__init__() has been deprecated. Provide PKIClient instead.
WARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1639: The PKIConnection parameter in AccountClient.__init__() has been deprecated. Provide PKIClient instead.
ERROR: 'str' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/pki/server/pkiserver.py", line 41, in <module>
    cli.execute(sys.argv[1:])
    ~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pki/server/cli/__init__.py", line 159, in execute
    module.execute(argv, args=args)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pki/server/cli/cert.py", line 1432, in execute
    instance.cert_create(
    ~~~~~~~~~~~~~~~~~~~~^
        serial=serial, renew=True, output=output, username=agent_uid,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        password=agent_pass, secure_port=port,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        client_nssdb=instance.nssdb_dir)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pki/server/instance.py", line 942, in cert_create
    pki.server.PKIServer.renew_certificate(connection, new_cert_file, serial)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pki/server/__init__.py", line 1776, in renew_certificate
    logger.info('Renewing cert %s', hex(serial))
                                    ~~~^^^^^^^^
TypeError: 'str' object cannot be interpreted as an integer

Enter "yes" to proceed: Proceeding.
ipapython.admintool: DEBUG:   File "/usr/lib/python3.13/site-packages/ipapython/admintool.py", line 219, in execute
    return_value = self.run()
  File "/usr/lib/python3.13/site-packages/ipaserver/install/ipa_cert_fix.py", line 152, in run
    run_cert_fix(certs, extra_certs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/ipaserver/install/ipa_cert_fix.py", line 375, in run_cert_fix
    ipautil.run(cmd, raiseonerr=True)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/ipapython/ipautil.py", line 594, in run
    raise CalledProcessError(
        p.returncode, arg_string, output_log, error_log
    )

ipapython.admintool: DEBUG: The ipa-cert-fix command failed, exception: CalledProcessError: CalledProcessError(Command ['pki-server', 'cert-fix', '--ldapi-socket', '/run/slapd-UFREEIPA-TEST.socket', '--agent-uid', 'ipara', '--cert', 'sslserver', '--cert', 'subsystem', '--cert', 'ca_ocsp_signing', '--cert', 'ca_audit_signing', '--extra-cert', '326927193689702498853940060656072272345', '--extra-cert', '40488042564141254294002070329107376970', '--extra-cert', '86013533104087455805498665371639067193', '--extra-cert', '86743368863325796666336266970492023132'] returned non-zero exit status 1: 'SASL/EXTERNAL authentication started\nSASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth\nSASL SSF: 0\nWARNING: No selftests configured in /var/lib/pki/pki-tomcat/conf/acme/CS.cfg (selftests.container.order.startup).\nSASL/EXTERNAL authentication started\nSASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth\nSASL SSF: 0\nSASL/EXTERNAL authentication started\nSASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth\nSASL SSF: 0\nWARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1639: The PKIConnection parameter in AccountClient.__init__() has been deprecated. Provide PKIClient instead.\nWARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1779: The PKIConnection parameter in CertClient.__init__() has been deprecated. Provide PKIClient instead.\nWARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1639: The PKIConnection parameter in AccountClient.__init__() has been deprecated. Provide PKIClient instead.\nWARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1779: The PKIConnection parameter in CertClient.__init__() has been deprecated. Provide PKIClient instead.\nWARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1639: The PKIConnection parameter in AccountClient.__init__() has been deprecated. Provide PKIClient instead.\nWARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1779: The PKIConnection parameter in CertClient.__init__() has been deprecated. Provide PKIClient instead.\nWARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1639: The PKIConnection parameter in AccountClient.__init__() has been deprecated. Provide PKIClient instead.\nWARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1779: The PKIConnection parameter in CertClient.__init__() has been deprecated. Provide PKIClient instead.\nWARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1639: The PKIConnection parameter in AccountClient.__init__() has been deprecated. Provide PKIClient instead.\nERROR: \'str\' object cannot be interpreted as an integer\nTraceback (most recent call last):\n  File "/usr/lib/python3.13/site-packages/pki/server/pkiserver.py", line 41, in <module>\n    cli.execute(sys.argv[1:])\n    ~~~~~~~~~~~^^^^^^^^^^^^^^\n  File "/usr/lib/python3.13/site-packages/pki/server/cli/__init__.py", line 159, in execute\n    module.execute(argv, args=args)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.13/site-packages/pki/server/cli/cert.py", line 1432, in execute\n    instance.cert_create(\n    ~~~~~~~~~~~~~~~~~~~~^\n        serial=serial, renew=True, output=output, username=agent_uid,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        password=agent_pass, secure_port=port,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        client_nssdb=instance.nssdb_dir)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.13/site-packages/pki/server/instance.py", line 942, in cert_create\n    pki.server.PKIServer.renew_certificate(connection, new_cert_file, serial)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.13/site-packages/pki/server/__init__.py", line 1776, in renew_certificate\n    logger.info(\'Renewing cert %s\', hex(serial))\n                                    ~~~^^^^^^^^\nTypeError: \'str\' object cannot be interpreted as an integer\n')
ipapython.admintool: ERROR: CalledProcessError(Command ['pki-server', 'cert-fix', '--ldapi-socket', '/run/slapd-UFREEIPA-TEST.socket', '--agent-uid', 'ipara', '--cert', 'sslserver', '--cert', 'subsystem', '--cert', 'ca_ocsp_signing', '--cert', 'ca_audit_signing', '--extra-cert', '326927193689702498853940060656072272345', '--extra-cert', '40488042564141254294002070329107376970', '--extra-cert', '86013533104087455805498665371639067193', '--extra-cert', '86743368863325796666336266970492023132'] returned non-zero exit status 1: 'SASL/EXTERNAL authentication started\nSASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth\nSASL SSF: 0\nWARNING: No selftests configured in /var/lib/pki/pki-tomcat/conf/acme/CS.cfg (selftests.container.order.startup).\nSASL/EXTERNAL authentication started\nSASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth\nSASL SSF: 0\nSASL/EXTERNAL authentication started\nSASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth\nSASL SSF: 0\nWARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1639: The PKIConnection parameter in AccountClient.__init__() has been deprecated. Provide PKIClient instead.\nWARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1779: The PKIConnection parameter in CertClient.__init__() has been deprecated. Provide PKIClient instead.\nWARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1639: The PKIConnection parameter in AccountClient.__init__() has been deprecated. Provide PKIClient instead.\nWARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1779: The PKIConnection parameter in CertClient.__init__() has been deprecated. Provide PKIClient instead.\nWARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1639: The PKIConnection parameter in AccountClient.__init__() has been deprecated. Provide PKIClient instead.\nWARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1779: The PKIConnection parameter in CertClient.__init__() has been deprecated. Provide PKIClient instead.\nWARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1639: The PKIConnection parameter in AccountClient.__init__() has been deprecated. Provide PKIClient instead.\nWARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1779: The PKIConnection parameter in CertClient.__init__() has been deprecated. Provide PKIClient instead.\nWARNING: /usr/lib/python3.13/site-packages/pki/server/__init__.py:1639: The PKIConnection parameter in AccountClient.__init__() has been deprecated. Provide PKIClient instead.\nERROR: \'str\' object cannot be interpreted as an integer\nTraceback (most recent call last):\n  File "/usr/lib/python3.13/site-packages/pki/server/pkiserver.py", line 41, in <module>\n    cli.execute(sys.argv[1:])\n    ~~~~~~~~~~~^^^^^^^^^^^^^^\n  File "/usr/lib/python3.13/site-packages/pki/server/cli/__init__.py", line 159, in execute\n    module.execute(argv, args=args)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.13/site-packages/pki/server/cli/cert.py", line 1432, in execute\n    instance.cert_create(\n    ~~~~~~~~~~~~~~~~~~~~^\n        serial=serial, renew=True, output=output, username=agent_uid,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        password=agent_pass, secure_port=port,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        client_nssdb=instance.nssdb_dir)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.13/site-packages/pki/server/instance.py", line 942, in cert_create\n    pki.server.PKIServer.renew_certificate(connection, new_cert_file, serial)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.13/site-packages/pki/server/__init__.py", line 1776, in renew_certificate\n    logger.info(\'Renewing cert %s\', hex(serial))\n                                    ~~~^^^^^^^^\nTypeError: \'str\' object cannot be interpreted as an integer\n')
ipapython.admintool: ERROR: The ipa-cert-fix command failed.
Exit code: 1
```

**Comment by edewata** [comment]
@flo-renaud It should be fixed now. Please try again.

BTW, how are you running your test? This is what we have:
https://github.com/dogtagpki/pki/blob/master/.github/workflows/ipa-renewal-test.yml
We're only testing it with short-lived PKI certs so `ipa-cert-fix` doesn't add the `--extra-cert` params.

**Comment by flo-renaud** [comment]
@edewata 

✅  Tested with dogtag-pki-server-11.6.0-0.3.alpha3.20250129090244UTC.080cc976.fc41.noarch, the test is now green.

Our test is located [here](https://pagure.io/freeipa/blob/master/f/ipatests/test_integration/test_ipa_cert_fix.py)
The test performs an installation of IPA server, moves the date in the future after PKI, LDAP and HTTP certs have expired, then calls ipa-cert-fix.

**Comment by edewata** [comment]
Thanks for the info. We're testing PKI in a container so we might need to use a third-party library like this:
https://stackoverflow.com/questions/29556879/is-it-possible-change-date-in-docker-container
