### ISSUE TITLE
pki-cert-fix fails with AttributeError: 'Namespace' object has no attribute 'ldap_socket'. Did you mean: 'ldapi_socket'?'

### ISSUE THREAD

**Issue by flo-renaud** [dogtagpki/pki#4917]
IPA nightly tests using the copr repo @pki/master are failing in the call to pki-cert-fix.

See for instance in PR #[4257](https://github.com/freeipa-pr-ci2/freeipa/pull/4257), the test pki-fedora/test_cert_fix with the following [report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/992e00e8-c0b1-11ef-801e-fa163ec045e3/report.html?sort=result) and  [Details](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/992e00e8-c0b1-11ef-801e-fa163ec045e3).

The test is calling ipa-cert-fix, which internally calls pki-cert-fix:
```
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557 ipapython.ipautil: DEBUG: Starting external process
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557 ipapython.ipautil: DEBUG: args=['pki-server', 'cert-fix', '--ldapi-socket', '/run/slapd-IPA-TEST.socket', '--agent-uid', 'ipara', '--cert', 'sslserver', '--cert', 'subsystem', '--cert', 'ca_ocsp_signing', '--cert', 'ca_audit_signing', '--extra-cert', '26191167921221075132609118771215754311', '--extra-cert', '6879485010672219218028962308204980292', '--extra-cert', '62985175563682748269956512926575395747', '--extra-cert', '94425030329991856039355944210261796575']
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557 ipapython.ipautil: DEBUG: Process finished, return code=1
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557 ipapython.ipautil: DEBUG: stdout=
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557 ipapython.ipautil: DEBUG: stderr=ERROR: 'Namespace' object has no attribute 'ldap_socket'
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557 Traceback (most recent call last):
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557   File "/usr/lib/python3.13/site-packages/pki/server/pkiserver.py", line 41, in <module>
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557     cli.execute(sys.argv)
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557     ~~~~~~~~~~~^^^^^^^^^^
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557   File "/usr/lib/python3.13/site-packages/pki/server/cli/__init__.py", line 143, in execute
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557     super().execute(args)
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557     ~~~~~~~~~~~~~~~^^^^^^
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557   File "/usr/lib/python3.13/site-packages/pki/cli/__init__.py", line 217, in execute
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557     module.execute(module_args)
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557     ~~~~~~~~~~~~~~^^^^^^^^^^^^^
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557   File "/usr/lib/python3.13/site-packages/pki/cli/__init__.py", line 217, in execute
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557     module.execute(module_args)
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557     ~~~~~~~~~~~~~~^^^^^^^^^^^^^
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557   File "/usr/lib/python3.13/site-packages/pki/server/cli/cert.py", line 1239, in execute
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557     if args.ldap_socket and args.ldap_url:
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557        ^^^^^^^^^^^^^^^^
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557 AttributeError: 'Namespace' object has no attribute 'ldap_socket'. Did you mean: 'ldapi_socket'?
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557 
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557 ipapython.admintool: DEBUG:   File "/usr/lib/python3.13/site-packages/ipapython/admintool.py", line 180, in execute
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557     return_value = self.run()
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557   File "/usr/lib/python3.13/site-packages/ipaserver/install/ipa_cert_fix.py", line 152, in run
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557     run_cert_fix(certs, extra_certs)
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557   File "/usr/lib/python3.13/site-packages/ipaserver/install/ipa_cert_fix.py", line 375, in run_cert_fix
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557     ipautil.run(cmd, raiseonerr=True)
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557   File "/usr/lib/python3.13/site-packages/ipapython/ipautil.py", line 594, in run
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557     raise CalledProcessError(
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557         p.returncode, arg_string, output_log, error_log
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557     )
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557 
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557 Enter "yes" to proceed: Proceeding.
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557 ipapython.admintool: DEBUG: The ipa-cert-fix command failed, exception: CalledProcessError: CalledProcessError(Command ['pki-server', 'cert-fix', '--ldapi-socket', '/run/slapd-IPA-TEST.socket', '--agent-uid', 'ipara', '--cert', 'sslserver', '--cert', 'subsystem', '--cert', 'ca_ocsp_signing', '--cert', 'ca_audit_signing', '--extra-cert', '26191167921221075132609118771215754311', '--extra-cert', '6879485010672219218028962308204980292', '--extra-cert', '62985175563682748269956512926575395747', '--extra-cert', '94425030329991856039355944210261796575'] returned non-zero exit status 1: 'ERROR: \'Namespace\' object has no attribute \'ldap_socket\'\nTraceback (most recent call last):\n  File "/usr/lib/python3.13/site-packages/pki/server/pkiserver.py", line 41, in <module>\n    cli.execute(sys.argv)\n    ~~~~~~~~~~~^^^^^^^^^^\n  File "/usr/lib/python3.13/site-packages/pki/server/cli/__init__.py", line 143, in execute\n    super().execute(args)\n    ~~~~~~~~~~~~~~~^^^^^^\n  File "/usr/lib/python3.13/site-packages/pki/cli/__init__.py", line 217, in execute\n    module.execute(module_args)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File "/usr/lib/python3.13/site-packages/pki/cli/__init__.py", line 217, in execute\n    module.execute(module_args)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File "/usr/lib/python3.13/site-packages/pki/server/cli/cert.py", line 1239, in execute\n    if args.ldap_socket and args.ldap_url:\n       ^^^^^^^^^^^^^^^^\nAttributeError: \'Namespace\' object has no attribute \'ldap_socket\'. Did you mean: \'ldapi_socket\'?\n')
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557 ipapython.admintool: ERROR: CalledProcessError(Command ['pki-server', 'cert-fix', '--ldapi-socket', '/run/slapd-IPA-TEST.socket', '--agent-uid', 'ipara', '--cert', 'sslserver', '--cert', 'subsystem', '--cert', 'ca_ocsp_signing', '--cert', 'ca_audit_signing', '--extra-cert', '26191167921221075132609118771215754311', '--extra-cert', '6879485010672219218028962308204980292', '--extra-cert', '62985175563682748269956512926575395747', '--extra-cert', '94425030329991856039355944210261796575'] returned non-zero exit status 1: 'ERROR: \'Namespace\' object has no attribute \'ldap_socket\'\nTraceback (most recent call last):\n  File "/usr/lib/python3.13/site-packages/pki/server/pkiserver.py", line 41, in <module>\n    cli.execute(sys.argv)\n    ~~~~~~~~~~~^^^^^^^^^^\n  File "/usr/lib/python3.13/site-packages/pki/server/cli/__init__.py", line 143, in execute\n    super().execute(args)\n    ~~~~~~~~~~~~~~~^^^^^^\n  File "/usr/lib/python3.13/site-packages/pki/cli/__init__.py", line 217, in execute\n    module.execute(module_args)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File "/usr/lib/python3.13/site-packages/pki/cli/__init__.py", line 217, in execute\n    module.execute(module_args)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File "/usr/lib/python3.13/site-packages/pki/server/cli/cert.py", line 1239, in execute\n    if args.ldap_socket and args.ldap_url:\n       ^^^^^^^^^^^^^^^^\nAttributeError: \'Namespace\' object has no attribute \'ldap_socket\'. Did you mean: \'ldapi_socket\'?\n')
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:557 ipapython.admintool: ERROR: The ipa-cert-fix command failed.
DEBUG    ipatests.pytest_ipa.integration.host.Host.master.cmd62:transport.py:217 Exit code: 1
```

The regressions seems caused by commit https://github.com/dogtagpki/pki/commit/2b1ae68acc639333e52e351e4c3da964317c51a5 . The help mentions `--ldapi-socket`, not `--ldap-socket`.

**Comment by edewata** [comment]
@flo-renaud sorry, this issue was closed automatically by GitHub when I pushed the [fix](https://github.com/dogtagpki/pki/commit/bdcd55aa23d767c7a80129270c26f8de581476bc). please feel free to reopen if this is still a problem.
